"""Add profile fields to users

Revision ID: 602be4cd0a23
Revises: 8b2c3d4e5f6a
Create Date: 2026-03-11 04:29:37.895195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602be4cd0a23'
down_revision: Union[str, None] = '8b2c3d4e5f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dietary_prefs', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('loyalty_programs', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'loyalty_programs')
    op.drop_column('users', 'dietary_prefs')
    # ### end Alembic commands ###
